# Generated by Django 4.2 on 2023-04-21 18:23

from django.db import migrations, models
import poll.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('prev_hash', models.CharField(blank=True, max_length=64)),
                ('merkle_hash', models.CharField(blank=True, max_length=64)),
                ('self_hash', models.CharField(blank=True, max_length=64)),
                ('nonce', models.IntegerField(null=True)),
                ('timestamp', models.FloatField(default=poll.models.get_time)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('public_key_n', models.CharField(max_length=320)),
                ('public_key_e', models.IntegerField(default=0)),
                ('reputation', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('eventID', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('count', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('voter_public_key_n', models.CharField(max_length=320)),
                ('vote', models.IntegerField(default=0)),
                ('timestamp', models.FloatField(default=poll.models.get_time)),
                ('block_id', models.IntegerField(null=True)),
            ],
        ),
    ]
