# Generated by Django 4.2 on 2023-04-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_rename_name_event_occurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventName',
            field=models.CharField(default='congestion', max_length=100),
            preserve_default=False,
        ),
    ]
