# Generated by Django 4.2 on 2023-04-26 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_event_eventname'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='creator_public_key_n',
            field=models.CharField(default='133508894535468383976465296530272724387711568263596507635288747611540951899974339610742411297912525826400578196732396472938603003348807118176193127656396909906827900902565869436550697868759598017176450909441967022598856731670993890051912696148209965192551849038078358945678337122307755281528100451216877403601', max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=133508894535468383976465296530272724387711568263596507635288747611540951899974339610742411297912525826400578196732396472938603003348807118176193127656396909906827900902565869436550697868759598017176450909441967022598856731670993890051912696148209965192551849038078358945678337122307755281528100451216877403601, max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='location',
            field=models.CharField(default='shashank', max_length=320),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='transaction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='car',
            name='public_key_e',
            field=models.IntegerField(default=65537),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote',
            field=models.IntegerField(default=2),
        ),
    ]
